#!/usr/bin/env python
"""Aggregate multilead JSON tables into a single RESULTS_SUMMARY.md."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from config import FIGS, TABLES


def main():
    files = sorted(TABLES.glob("multilead_*.json"))
    if not files:
        raise SystemExit("No multilead_*.json found. Run run_multilead.py first.")
    lines = [
        "# Ocean-DO-Forecast · Results summary",
        "",
        "Auto-generated by `scripts/export_summary.py`.",
        "",
    ]
    for fp in files:
        data = json.loads(fp.read_text(encoding="utf-8"))
        lines += [
            f"## `{fp.name}`",
            "",
            f"- Region: `{data.get('region')}`",
            f"- Cube: `{data.get('cube_source')}`",
            f"- Sparse: `{data.get('sparse')}`",
            f"- Blend weights: `{data.get('blend_weights')}`",
            "",
            "| Lead | Best model (RMSE) | RMSE | Hypoxia F1 |",
            "|---:|---|---:|---:|",
        ]
        by_lead = {}
        for r in data["metrics"]:
            by_lead.setdefault(r["lead_months"], []).append(r)
        for lead, rows in sorted(by_lead.items()):
            best = min(rows, key=lambda x: x["rmse"])
            lines.append(
                f"| {lead} | {best['model']} | {best['rmse']:.3f} | {best['hypoxia_f1']:.3f} |"
            )
        lines.append("")
    # figures index
    figs = sorted(FIGS.glob("*.png")) if FIGS.exists() else []
    if figs:
        lines += ["## Figures", ""]
        for f in figs:
            lines.append(f"- `{f.relative_to(ROOT)}`")
        lines.append("")
    out = TABLES / "RESULTS_SUMMARY.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"[summary] wrote {out}")


if __name__ == "__main__":
    main()
